#include<stdio.h>
int n,m;
long long int a[100][2000],sum1=0,sum2[2000],sumx=0,ej1[101],ej2[2001],xb,xs,xx;
const int N=998244353;
int main()
{
	freopen("meal.in","r",stdin);
	freopen("meal.out","w",stdout);
	int i,j;
	scanf("%d%d",&n,&m);
	for(i=0;i<n;i++)
	{
		for(j=0;j<m;j++)
		{
			scanf("%lld",&a[i][j]);
		}
	}
	ej1[n]=1;
	ej2[m]=1;
	while(ej1[0]==0)
	{
		for(i=0;i<m;i++)
		{
			ej2[i]=0;
		}
		ej2[m]=1;
		while(ej2[0]==0)
		{
			xx=0;
			for(i=0;xx==0&&i<n;i++)
			{
				xs=0;
				if(ej1[i+1]==1)
				{
					for(j=0;xx==0&&j<m;j++)
					{
						if(ej2[j+1]==1&&xs<2&&a[i][j]>0)
						{
							xs=xs+a[i][j];
						}
						if(xs>1)
						{
							break;
						}
					}
				}
				if(xs>1)
				{
					break;
				}
			}
			if(xs<2)
			{
				xx=1;
			}
			for(i=0;xx==0&&i<n;i++)
			{
				xb=0;
				xs=0;
				if(ej1[i+1]==1)
				{
					for(j=0;xx==0&&j<m;j++)
					{
						if(ej2[j+1]==1&&a[i][j]>0)
						{
							xs++;
						}
						if(xs>1)
						{
							xb=1;
							xx=1;
						}
					}
				}
			}
			sum1=0;
			for(i=0;xx==0&&i<m;i++)
			{
				sum2[i]=0;
			}
			for(i=0;xx==0&&i<n;i++)
			{
				if(ej1[i+1]==1)
				{
					for(j=0;xx==0&&j<m;j++)
					{
						if(ej2[j+1]==1&&a[i][j])
						{
							sum1=(sum1+a[i][j])%N;
							sum2[j]=(sum2[j]+((a[i][j]%N)*2)%N)%N;
						}
					}
				}
			}
			for(i=0;xx==0&&i<m;i++)
			{
				if(sum2[i]>sum1)
				{
					xb=1;
					xx=1;
					break;
				}
			}
			if(xx==0)
			{
				sumx=(sumx+1)%N;
			}
			for(i=m;i>0&&ej2[i]==1;i--)
			{
			}
			ej2[i]=1;
			for(j=i+1;j<=m;j++)
			{
				ej2[j]=0;
			}
		}
		for(i=n;i>0&&ej1[i]==1;i--)
		{
		}
		ej1[i]=1;
		for(j=i+1;j<=n;j++)
		{
			ej1[j]=0;
		}
	}
	printf("%d",4*n*n);
	fclose(stdin);
	fclose(stdout);
	return 0;
}
